### ISSUE TITLE
Failed to activate the 0-env package

### ISSUE THREAD

**Issue by VernonCrabtree** [andystanton/0-env#1]
[Enter steps to reproduce:]

1. Install Atom on Windows
2. Install the 0-env package
3. Start Atom

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [0-env](https://github.com/andystanton/0-env) package 1.0.1

### Stack Trace

Failed to activate the 0-env package

```
At Command failed: $SHELL --login -i -c "env; exit"
'$SHELL' is not recognized as an internal or external command,
operable program or batch file.


Error: Command failed: $SHELL --login -i -c "env; exit"
'$SHELL' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:613:13)
    at execSync (child_process.js:653:13)
    at ELECTRON_ASAR.js:721:23
    at Object.activate (/packages/0-env/lib/0-env.js:9:5)
    at Package.activateNow (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3028240)
    at measure (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3027652)
    at Package.measure (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3025283)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3027512)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3027455)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:382481)
    at config.transactAsync (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:382097)
    at Config.transactAsync (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:332284)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:382047)
    at PackageManager.activate (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:381665)
    at t.loadState.then (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:1:648400)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
0-env 1.0.1 
atom-ide-ui 0.13.0 
auto-run 0.2.1 
autocomplete-python 1.11.0 
autocomplete-robot-framework 3.6.0 
env-from-shell 0.3.0 
hyperclick 0.0.0 
hyperclick-robot-framework 1.8.0 
ide-python 1.1.0 
language-robot-framework 2.4.0 
python-autopep8 0.1.3 
python-tools 0.6.9 
script 3.18.1 
sonarlint 1.2.1 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by piccolbo** [comment]
Same on OS X high sierra atom 1.40.1. Suspect using fish shell may be throwing a curve ball here.

**Comment by andystanton** [comment]
Hi @VernonCrabtree and @piccolbo, apologies for some reason I wasn't watching this repo any more and missed this issue. There was a PR raised recently, and in verifying it, I discovered that Atom seems to be loading my environment variables from both the desktop icon and the `atom` terminal command without the need for `0-env`.

I'm using macos 10.15.4 with Atom 1.45.0 (and fish shell incidentally) so was thinking that perhaps there is no need for this package any more. Perhaps you could evaluate if it's still required for your use cases?
